<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Package properties -->
    <PackageId>Vettvangur.DictionaryHelper</PackageId>
    <Version>5.0.2</Version>
    <Title>Vettvangur Dictionary Helper</Title>
    <Authors>Vettvangur</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Vettvangur/Vettvangur.DictionaryHelper/tree/17</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Vettvangur/Vettvangur.DictionaryHelper/tree/17</RepositoryUrl>
    <Description>Umbraco helper to fetch dictionary items for Umbraco</Description>
    <PackageReleaseNotes>Release for Umbraco 17</PackageReleaseNotes>
    <Copyright>Copyright 2023</Copyright>
    <PackageTags>Umbraco Dictionary</PackageTags>

    <!-- Icon & README -->
    <PackageIcon>VV_Logo.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <!-- Symbols & SourceLink -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>

    <!-- Build / docs -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>

    <!-- Optional QoL -->
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <!-- <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild> -->
    
  </PropertyGroup>

  <!-- Package icon -->
  <ItemGroup>
    <None Include="..\VV_Logo.png" Pack="true" PackagePath="images\"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="../VV_Logo.png" Pack="true" PackagePath=""/>
    <None Include="../README.md" Pack="true" PackagePath=""/>
    <None Include="../Changelog.md" Pack="true" PackagePath=""/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All"/>
    <PackageReference Include="Umbraco.Cms.Core" Version="17.0.2"/>
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="17.0.2"/>
  </ItemGroup>

</Project>
